name = "ChaosServer"
author = "JefNo"
version = "0.1.0"
pack-format = "packwiz:1.1.0"

[index]
file = "index.toml"
hash-format = "sha256"
hash = "03daa042bd5d1ec79dfc648ecfb46dacb52a422c42eb3d35280825fa2944ed8e"

[versions]
forge = "14.23.5.2864"
minecraft = "1.12.2"
